name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      ENABLED_DETEKT: false
      ENABLED_COPY_DOCS: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Displays a message only for demo
      - name: "Display message"
        run: echo "Hola mundo!"

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up JDK 17 for Detekt and tests
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: "Detekt run"
        if: ${{ env.ENABLED_DETEKT == 'true' }}
        run: |
          echo "Running Detekt..."
          ./gradlew detekt

      # Custom tasks
      - name: "Custom tasks"
        run: | # el pipe es necesario para multilinea
          # unitTest
          echo "Running unit tests..."
          ./gradlew test          
          
          # Copy docs to build output
          echo "Copying docs..."
          run ./gradlew copy