name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# cancela las peticiones duplicadas a la misma branch
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      ENABLED_DETEKT: false
      ENABLED_COPY_DOCS: false
      ENABLED_TEST: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Displays a message only for demo
      - name: "Display variables"
        run: echo "enabled_detekt=${{env.ENABLED_DETEKT}}, enabled_copy_docs=${{env.ENABLED_COPY_DOCS}}, enabled_test=${{env.ENABLED_TEST}}"

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up JDK 17 for Detekt and tests
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: "Detekt run"
        if: ${{ env.ENABLED_DETEKT == 'true' }}
        run: | # el pipe es necesario para multilinea
          echo "Running Detekt..."
          ./gradlew detekt

      - name: "UnitTest run"
        if: ${{ env.ENABLED_TEST == 'true' }}
        run: | 
          echo "Running unit tests..."
          ./gradlew test    

      - name: "Copy docs"
        if: ${{ env.ENABLED_COPY_DOCS == 'true' }}
        run: |
          echo "Copying docs..."
          run ./gradlew copy